version: '3'
services:
  redis-server:
    image: 'redis'
  node-app:
    # restart: "no"
    # restart: on-failuar
    # restart: unless-stopped
    restart: always
    build: .
    ports:
      - "4001:8081"